export interface ITestOnlyOneSerialRecord {
  ser1?: number,
  i1: number,
  i2?: number | null,
  permanent?: boolean | null,
  si?: number | null,
  j?: any | null,
  jb?: any | null,
  a_i?: number[] | null,
  a_t?: string[] | null,
  a_b?: boolean[] | null,
  a_num?: number[] | null,
  a_real?: number[] | null,
  a_f?: number[] | null,
  a_money?: number[] | null,
  a_vc?: string[] | null,
  a_si?: number[] | null,
  a_time?: (string | Date | number)[] | null,
  a_date?: (string | Date | number)[] | null,
  a_ts?: (string | Date | number)[] | null,
  a_tz?: (string | Date | number)[] | null,
}
