export interface ITestTableSchemaRecord {
  ser1?: string,
  ser2?: string,
  i1?: string,
  i2?: string | null,
  si1: number,
  vc1: string,
  dtz1?: string | Date | number,
  time1: string,
  bool1?: boolean,
  bool2?: boolean | null,
  arr_int?: string[] | null,
  arr_str?: string[] | null,
  decimal?: number | null,
  numeric?: number | null,
  money?: string | null,
  real?: number | null,
  double_precision?: string | null,
  bytea?: string | null,
  gen1?: number | null,
}
