export interface ITestTableSchemaRecord {
  ser1: number,
  i1?: number,
  i2?: number | null,
  i3?: number | null,
  si1: number,
  vc1?: string,
  dt1?: string | Date | number,
  dt2?: string | Date | number,
  dtz?: string | Date | number,
  time1?: string | Date | number | null,
  bool1?: boolean,
  comp1: boolean,
  pers1: boolean,
}
