---
logger:
  level: verbose
timezone: Europe/Moscow

db:
  mssql:
    options:
      options:
        enableArithAbort: false
      pool:
        max: 100
        min: 1
        idleTimeoutMillis: 30000
        acquireTimeoutMillis: 30000
        createTimeoutMillis: 30000
        destroyTimeoutMillis: 30000
        reapIntervalMillis: 30000
        createRetryIntervalMillis: 30000
      trustServerCertificate: true
      stream: false
      parseJSON: false
      requestTimeout: 3600000
      connectionTimeout: 60000
    dbs:
      myMssqlDb:
        server: hostOrIp
        port: 1433
        options:
          multiSubnetFailover: true
        database: dbName
        user: userName
        password: userPassword
  postgres:
    options:
      connectionTimeoutMillis: 300000
      idleTimeoutMillis: 30000
      max: 10
      statement_timeout: 30000
      query_timeout: 30000
    dbs:
      myPgDb:
        host: hostOrIp
        port: 5432
        database: dbName
        user: userName
        password: userPassword
